services:
  song-service:
    image: udnboss/song-service
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - DB_HOST=song-database
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD

  song-database:
    image: udnboss/song-database
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
