apiVersion: v1 
kind: ConfigMap
metadata:
  name: post-app-config
  namespace: my-namespace
data: # store environment variables for application deployments.
  NODE_ENV: "production"
  DB_HOST: "post-database"
  DB_PORT: "5432"
  USER_SERVICE_PORT: "3000"