apiVersion: v1
kind: Service
metadata:
  name: post-database
  namespace: my-namespace
spec:
  type: NodePort  # Exposes the service on all nodes' IP addresses with a random port
  ports:
  - port: 5432
  selector:
    app: post-postgres-db
