apiVersion: v1 
kind: ConfigMap
metadata:
  name: user-app-config
  namespace: my-namespace
data: # store environment variables for application deployments.
  NODE_ENV: "production"
  DB_HOST: "user-database"
  DB_PORT: "5432"