apiVersion: v1
kind: Service
metadata:
  name: user-database
  namespace: my-namespace
spec:
  type: NodePort  # Exposes the service on all nodes' IP addresses with a random port
  selector:
    app: user-postgres-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  
