apiVersion: v1 
kind: ConfigMap
metadata:
  name: user-db-init-scripts-config
  namespace: my-namespace
data: #sql scripts to init databases (create tables) 
  init.sql: |
    CREATE TABLE users (
      id SERIAL PRIMARY KEY,
      username VARCHAR(255) NOT NULL UNIQUE,
      amountOfPosts INTEGER NOT NULL DEFAULT 0
    );

    -- Insert Users
    INSERT INTO users (username) VALUES
      ('user1'),
      ('user2'),
      ('user3');
