# Use the official image as a parent image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER username
ENV POSTGRES_PASSWORD password
ENV POSTGRES_DB songdb

# Run the command inside your image filesystem
CMD ["postgres"]
